spring:
  data:
    mongodb:
      uri: ${MONBODB_URI:mongodb://mongodb:27017/sailfish}
      username: ${MONBODB_USERNAME}
      password: ${MONBODB_PASSWORD}
    redis:
      repositories.enabled: false
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
    pool:
      max-active: ${REDIS_POOL_MAX_ACTIVE:100}
      max-idle: ${REDIS_POOL_MAX_IDLE:8}
      max-wait: ${REDIS_POOL_MAX_WAIT:60000}

