server:
  port: 8080

info:
  app:
    version: dev-snapshot

gateway:
  version: dev-snapshot

spring:
  data:
    mongodb:
      uri: "mongodb://127.0.0.1:27017/oauth2"
      repositories.enabled: false
  redis:
    host: localhost
    port: 6379
    repositories.enabled: false

