server:
  port: 8080

info:
  app:
    version: ${OAUTH2_VERSION:dev-snapshot}

gateway:
  version: ${OAUTH2_VERSION:dev-snapshot}

spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/sailfish"
      repositories.enabled: false
  redis:
    host: localhost
    port: 6379
    repositories.enabled: false

