spring:
  data:
    mongodb:
      uri: ${MONBODB_URI:mongodb://mongodb:27017/sailfish}
      repositories.enabled: false
    redis:
      repositories.enabled: false
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    pool:
      max-active: ${REDIS_POOL_MAX_ACTIVE:100}
      max-idle: ${REDIS_POOL_MAX_IDLE:8}
      max-wait: ${REDIS_POOL_MAX_WAIT:60000}

